title: disco is not dead 
author: Rukaya A
email: rabdal2@uic.edu
description: > # this means to ignore newlines until "baseurl:"
 disco is not dead
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

